---
title: "In_ClassExercise4"
author: "Abhishek Singh"
published: "May 6 2023"
date-modified: "'r Sys.Date()'"
execute: 
  echo: true
  eval: true
  warning: false
---

```{r}
pacman::p_load(rstatix, gt, patchwork, tidyverse)
```

```{r}
exam_data<-read_csv("data/Exam_data.csv")
```

::: panel-tabset
## The Plot

```{r}
#| echo: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,aes(sample=ENGLISH))+ stat_qq() +stat_qq_line()

```

## The Code Chunk

```{r}
#| eval: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH))+
  stat_qq() +
  stat_qq_line()
```
:::

::: callout-note
We can see that the points deviate significantly from the straight diagonal line. This is a clear inidcation that the set of data is not normally distributed.
:::

### Comibining statistical graph and analysis table

Need to install webshot

::: panel-tabset
```{r}
#| echo: false
qq <- ggplot(exam_data,
       aes(sample=ENGLISH))+
  stat_qq() +
  stat_qq_line()

sw_t <- exam_data %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp,native=TRUE)

qq + table_png
```
:::
